version: '3.3'

services:
  impact-graph:
    #see https://github.com/docker/build-push-action/tree/releases/v1#tag_with_ref

    # is sometime you want to rollback you can change the tag manually in server( not commit to git)
    # from master to your desired commit hash and the run command:
    # 1. docker-compose -f docker-compose-develop.yml pull
    # 2. docker-compose -f docker-compose-develop.yml down
    # 3. docker-compose -f docker-compose-develop.yml up -d
    image: ghcr.io/giveth/impact-graph:develop
    environment:
      - NODE_ENV=production
      - ENVIRONMENT=develop
      - LOG_PATH=/usr/src/app/logs/impact-graph.log
    restart: always
    volumes:
      # You should have a production.env file in the config folder
      - type: bind
        source: ./config
        target: /usr/src/app/config
      - type: bind
        source: ./logs
        target: /usr/src/app/logs
    ports:
      - "4000:4000"
    depends_on:
      - redis-giveth

  redis-giveth:
    # it's better to not using latest tag, maybe latest tag have some breaking changes
    image: bitnami/redis:5.0.9-debian-10-r142
    container_name: redis-giveth
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    volumes:
      - redis-data:/bitnami/redis/data

volumes:
  redis-data:
