const abi = [
  {
    inputs: [{ internalType: 'address', name: 'target', type: 'address' }],
    name: 'AddressEmptyCode',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'AddressInsufficientBalance',
    type: 'error',
  },
  { inputs: [], name: 'FailedInnerCall', type: 'error' },
  { inputs: [], name: 'InvalidInitialization', type: 'error' },
  {
    inputs: [{ internalType: 'string', name: 'funcSig', type: 'string' }],
    name: 'Module_OrchestratorCallbackFailed',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__BondingCurveBase__BuyingFunctionaltiesClosed',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__BondingCurveBase__FeeAmountToHigh',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__BondingCurveBase__InsufficientOutputAmount',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__BondingCurveBase__InvalidDepositAmount',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__BondingCurveBase__InvalidFeePercentage',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__BondingCurveBase__InvalidMinAmountOut',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__BondingCurveBase__InvalidRecipient',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__BondingCurveBase__InvalidWithdrawAmount',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__BondingCurveBase__TradeAmountTooLow',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'caller', type: 'address' },
    ],
    name: 'Module__CallerNotAuthorized',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__FM_BC_Bancor_Redeeming_VirtualSupply__CurveInteractionsMustBeClosed',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__FM_BC_Bancor_Redeeming_VirtualSupply__InvalidBancorFormula',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__FM_BC_Bancor_Redeeming_VirtualSupply__InvalidOrchestratorTokenWithdrawAmount',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__FM_BC_Bancor_Redeeming_VirtualSupply__InvalidReserveRatio',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__FM_BC_Bancor_Redeeming_VirtualSupply__InvalidTokenDecimal',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__FM_BC_Restricted_Bancor_Redeeming_VirtualSupply__FeatureDeactivated',
    type: 'error',
  },
  { inputs: [], name: 'Module__InvalidAddress', type: 'error' },
  { inputs: [], name: 'Module__InvalidMetadata', type: 'error' },
  { inputs: [], name: 'Module__InvalidOrchestratorAddress', type: 'error' },
  { inputs: [], name: 'Module__OnlyCallableByOrchestrator', type: 'error' },
  { inputs: [], name: 'Module__OnlyCallableByPaymentClient', type: 'error' },
  {
    inputs: [],
    name: 'Module__RedeemingBondingCurveBase__InsufficientCollateralForRedemption',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__RedeemingBondingCurveBase__SellingFunctionaltiesClosed',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__VirtualCollateralSupplyBase__AddResultsInOverflow',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__VirtualCollateralSupplyBase__SubtractResultsInUnderflow',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__VirtualCollateralSupplyBase__VirtualSupplyCannotBeZero',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__VirtualIssuanceSupplyBase__AddResultsInOverflow',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__VirtualIssuanceSupplyBase__SubtractResultsInUnderflow',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Module__VirtualIssuanceSupplyBase__VirtualSupplyCannotBeZero',
    type: 'error',
  },
  { inputs: [], name: 'NotInitializing', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'token', type: 'address' }],
    name: 'SafeERC20FailedOperation',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'newBuyFee',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'oldBuyFee',
        type: 'uint256',
      },
    ],
    name: 'BuyFeeUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint32',
        name: 'newBuyReserveRatio',
        type: 'uint32',
      },
      {
        indexed: false,
        internalType: 'uint32',
        name: 'oldBuyReserveRatio',
        type: 'uint32',
      },
    ],
    name: 'BuyReserveRatioSet',
    type: 'event',
  },
  { anonymous: false, inputs: [], name: 'BuyingDisabled', type: 'event' },
  { anonymous: false, inputs: [], name: 'BuyingEnabled', type: 'event' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint64',
        name: 'version',
        type: 'uint64',
      },
    ],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'issuanceToken',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint8',
        name: 'decimals',
        type: 'uint8',
      },
    ],
    name: 'IssuanceTokenSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'parentOrchestrator',
        type: 'address',
      },
      {
        components: [
          { internalType: 'uint256', name: 'majorVersion', type: 'uint256' },
          { internalType: 'uint256', name: 'minorVersion', type: 'uint256' },
          { internalType: 'uint256', name: 'patchVersion', type: 'uint256' },
          { internalType: 'string', name: 'url', type: 'string' },
          { internalType: 'string', name: 'title', type: 'string' },
        ],
        indexed: false,
        internalType: 'struct IModule_v1.Metadata',
        name: 'metadata',
        type: 'tuple',
      },
    ],
    name: 'ModuleInitialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'token',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint8',
        name: 'decimals',
        type: 'uint8',
      },
    ],
    name: 'OrchestratorTokenSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'ProjectCollateralFeeAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'receiver',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'ProjectCollateralFeeWithdrawn',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'token',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'treasury',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'feeAmount',
        type: 'uint256',
      },
    ],
    name: 'ProtocolFeeMinted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'token',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'treasury',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'feeAmount',
        type: 'uint256',
      },
    ],
    name: 'ProtocolFeeTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'newSellFee',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'oldSellFee',
        type: 'uint256',
      },
    ],
    name: 'SellFeeUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint32',
        name: 'newSellReserveRatio',
        type: 'uint32',
      },
      {
        indexed: false,
        internalType: 'uint32',
        name: 'oldSellReserveRatio',
        type: 'uint32',
      },
    ],
    name: 'SellReserveRatioSet',
    type: 'event',
  },
  { anonymous: false, inputs: [], name: 'SellingDisabled', type: 'event' },
  { anonymous: false, inputs: [], name: 'SellingEnabled', type: 'event' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint8',
        name: 'oldDecimals',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'uint8',
        name: 'newDecimals',
        type: 'uint8',
      },
    ],
    name: 'TokenDecimalsUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'receiver',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'depositAmount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'receivedAmount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'buyer',
        type: 'address',
      },
    ],
    name: 'TokensBought',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'receiver',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'depositAmount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'receivedAmount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'seller',
        type: 'address',
      },
    ],
    name: 'TokensSold',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: '_to', type: 'address' },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_amount',
        type: 'uint256',
      },
    ],
    name: 'TransferOrchestratorToken',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountAdded',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'newSupply',
        type: 'uint256',
      },
    ],
    name: 'VirtualCollateralAmountAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountSubtracted',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'newSupply',
        type: 'uint256',
      },
    ],
    name: 'VirtualCollateralAmountSubtracted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'newSupply',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'oldSupply',
        type: 'uint256',
      },
    ],
    name: 'VirtualCollateralSupplySet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountAdded',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'newSupply',
        type: 'uint256',
      },
    ],
    name: 'VirtualIssuanceAmountAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountSubtracted',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'newSupply',
        type: 'uint256',
      },
    ],
    name: 'VirtualIssuanceAmountSubtracted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'newSupply',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'oldSupply',
        type: 'uint256',
      },
    ],
    name: 'VirtualIssuanceSupplySet',
    type: 'event',
  },
  {
    inputs: [],
    name: 'CURVE_INTERACTION_ROLE',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_depositAmount', type: 'uint256' },
      { internalType: 'uint256', name: '_minAmountOut', type: 'uint256' },
    ],
    name: 'buy',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'buyFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_receiver', type: 'address' },
      { internalType: 'uint256', name: '_depositAmount', type: 'uint256' },
      { internalType: 'uint256', name: '_minAmountOut', type: 'uint256' },
    ],
    name: 'buyFor',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'buyIsOpen',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_depositAmount', type: 'uint256' },
    ],
    name: 'calculatePurchaseReturn',
    outputs: [{ internalType: 'uint256', name: 'mintAmount', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_depositAmount', type: 'uint256' },
    ],
    name: 'calculateSaleReturn',
    outputs: [
      { internalType: 'uint256', name: 'redeemAmount', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'closeBuy',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'closeSell',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'formula',
    outputs: [
      { internalType: 'contract IBancorFormula', name: '', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getIssuanceToken',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getReserveRatioForBuying',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getReserveRatioForSelling',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getStaticPriceForBuying',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getStaticPriceForSelling',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getVirtualCollateralSupply',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getVirtualIssuanceSupply',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'target', type: 'address' },
    ],
    name: 'grantModuleRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address[]', name: 'targets', type: 'address[]' },
    ],
    name: 'grantModuleRoleBatched',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'identifier',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract IOrchestrator_v1',
        name: 'orchestrator_',
        type: 'address',
      },
      {
        components: [
          { internalType: 'uint256', name: 'majorVersion', type: 'uint256' },
          { internalType: 'uint256', name: 'minorVersion', type: 'uint256' },
          { internalType: 'uint256', name: 'patchVersion', type: 'uint256' },
          { internalType: 'string', name: 'url', type: 'string' },
          { internalType: 'string', name: 'title', type: 'string' },
        ],
        internalType: 'struct IModule_v1.Metadata',
        name: 'metadata',
        type: 'tuple',
      },
      { internalType: 'bytes', name: 'configData', type: 'bytes' },
    ],
    name: 'init',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'forwarder', type: 'address' }],
    name: 'isTrustedForwarder',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'openBuy',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'openSell',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'orchestrator',
    outputs: [
      { internalType: 'contract IOrchestrator_v1', name: '', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'projectCollateralFeeCollected',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'target', type: 'address' },
    ],
    name: 'revokeModuleRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address[]', name: 'targets', type: 'address[]' },
    ],
    name: 'revokeModuleRoleBatched',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_depositAmount', type: 'uint256' },
      { internalType: 'uint256', name: '_minAmountOut', type: 'uint256' },
    ],
    name: 'sell',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'sellFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'sellIsOpen',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_receiver', type: 'address' },
      { internalType: 'uint256', name: '_depositAmount', type: 'uint256' },
      { internalType: 'uint256', name: '_minAmountOut', type: 'uint256' },
    ],
    name: 'sellTo',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_fee', type: 'uint256' }],
    name: 'setBuyFee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint32', name: '_reserveRatio', type: 'uint32' }],
    name: 'setReserveRatioForBuying',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint32', name: '_reserveRatio', type: 'uint32' }],
    name: 'setReserveRatioForSelling',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_fee', type: 'uint256' }],
    name: 'setSellFee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_virtualSupply', type: 'uint256' },
    ],
    name: 'setVirtualCollateralSupply',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_virtualSupply', type: 'uint256' },
    ],
    name: 'setVirtualIssuanceSupply',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'title',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'token',
    outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'to', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'transferOrchestratorToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'trustedForwarder',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'url',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'version',
    outputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_receiver', type: 'address' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
    ],
    name: 'withdrawProjectCollateralFee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];

export default abi;
