export const PROJECT_TITLE_MAX_LENGTH: number = 200;
export const PROJECT_DESCRIPTION_MAX_LENGTH: number = 35000;
export const PROJECT_UPDATE_CONTENT_MAX_LENGTH: number = 2000;
export const IMAGE_LINK_MAX_SIZE = 400;
export const IMPACT_LOCATION_MAX_SIZE = 200;
export const GIVBACKS_ELIGIBLE_MIN_DONATION_USD = 5;
